### PR TITLE
Answers added to  answers.txt file

### PR DESCRIPTION
**Pull request by kashrajiv**
Creating pull request for the answers written in the answers.txt file

### CODE REVIEW

**Comment by shivani6621** [comment]
Looks good to me 
For the 4th question I'd like to add that there can be multiple repositories too as an when needed according to the Project requirements. But generally we maintain only 1 repository.

**Comment by kashrajiv** [comment]
Modified the answers based on comments.

**Comment by shivani6621** [comment]
Looks Perfect. Accepting the PR

**Comment by kashrajiv** [comment]
Can you please review my answers please.

**Pull request merged**
